### ISSUE TITLE
Double read of volatile field

### ISSUE THREAD

**Issue by xdelsy** [JarvisCraft/padla#90]
The `valueSupplier` and `value` fields of `Lazy.DoubleCheckedLazy` are volatile. Volatile reading is much more expensive than plain, so it's better to store local references to values rather than read them again.
https://github.com/JarvisCraft/padla/blob/7c049851f92075f4419fe3cbff77dd47f2afb55a/java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java#L203
https://github.com/JarvisCraft/padla/blob/7c049851f92075f4419fe3cbff77dd47f2afb55a/java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java#L219
https://github.com/JarvisCraft/padla/blob/7c049851f92075f4419fe3cbff77dd47f2afb55a/java-commons/src/main/java/ru/progrm_jarvis/javacommons/lazy/Lazy.java#L228

**Comment by JarvisCraft** [comment]
This is required for thread-safety according to JMM
